export const SLOVAK_DISTRICTS = [
  "Bratislava I",
  "Bratislava II",
  "Bratislava III",
  "Bratislava IV",
  "Bratislava V",
  "Malacky",
  "Pezinok",
  "Senec",
  "Dunajská Streda",
  "Galanta",
  "Hlohovec",
  "Piešťany",
  "Senica",
  "Skalica",
  "Komárno",
  "Levice",
  "Nitra",
  "Nové Zámky",
  "Šaľa",
  "Topoľčany",
  "Zlaté Moravce",
  "Bánovce nad Bebravou",
  "Ilava",
  "Myjava",
  "Nové Mesto nad Váhom",
  "Partizánske",
  "Považská Bystrica",
  "Prievidza",
  "Púchov",
  "Trenčín",
  "Bytča",
  "Čadca",
  "Dolný Kubín",
  "Kysucké Nové Mesto",
  "Liptovský Mikuláš",
  "Martin",
  "Námestovo",
  "Ružomberok",
  "Turčianske Teplice",
  "Tvrdošín",
  "Žilina",
  "Banská Bystrica",
  "Banská Štiavnica",
  "Brezno",
  "Detva",
  "Krupina",
  "Lučenec",
  "Poltár",
  "Revúca",
  "Rimavská Sobota",
  "Veľký Krtíš",
  "Zvolen",
  "Žarnovica",
  "Žiar nad Hronom",
  "Bardejov",
  "Humenné",
  "Kežmarok",
  "Levoča",
  "Medzilaborce",
  "Poprad",
  "Prešov",
  "Sabinov",
  "Snina",
  "Svidník",
  "Stará Ľubovňa",
  "Stropkov",
  "Vranov nad Topľou",
  "Gelnica",
  "Košice I",
  "Košice II",
  "Košice III",
  "Košice IV",
  "Košice-okolie",
  "Michalovce",
  "Rožňava",
  "Sobrance",
  "Spišská Nová Ves",
  "Trebišov",
] as const;
